// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSSystemWebAPI.Models;

#nullable disable

namespace POSSystemWebAPI.Migrations
{
    [DbContext(typeof(POSDbContext))]
    [Migration("20260712070730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POSSystemWebAPI.Models.ItemCategory", b =>
                {
                    b.Property<int>("ItemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCategoryId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Item")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemCategoryId");

                    b.ToTable("Item_Category");

                    b.HasData(
                        new
                        {
                            ItemCategoryId = 1,
                            IsActive = true,
                            Item = "Mango"
                        },
                        new
                        {
                            ItemCategoryId = 2,
                            IsActive = true,
                            Item = "Apple"
                        },
                        new
                        {
                            ItemCategoryId = 3,
                            IsActive = true,
                            Item = "Banana"
                        },
                        new
                        {
                            ItemCategoryId = 4,
                            IsActive = true,
                            Item = "Orange"
                        },
                        new
                        {
                            ItemCategoryId = 5,
                            IsActive = true,
                            Item = "Grapes"
                        },
                        new
                        {
                            ItemCategoryId = 6,
                            IsActive = true,
                            Item = "Kiwi"
                        },
                        new
                        {
                            ItemCategoryId = 7,
                            IsActive = true,
                            Item = "Strawberry"
                        });
                });

            modelBuilder.Entity("POSSystemWebAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Item_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("FreeQuantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Margin")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("StandardCost")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("StandardPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("TotalSelling")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Order_Item");
                });

            modelBuilder.Entity("POS_System_Web_API.Models.Entities.LocationDetail", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Location_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Location_Code");

                    b.Property<string>("LocationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Location_Name");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationCode")
                        .IsUnique();

                    b.ToTable("Location_Details");
                });

            modelBuilder.Entity("POSSystemWebAPI.Models.OrderItem", b =>
                {
                    b.HasOne("POSSystemWebAPI.Models.ItemCategory", "ItemCategory")
                        .WithMany()
                        .HasForeignKey("ItemCategoryId");

                    b.HasOne("POS_System_Web_API.Models.Entities.LocationDetail", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("ItemCategory");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
